import React, { useState } from 'react';
import { Download, FileText, CheckCircle2, AlertTriangle, ShieldCheck, Eye, Calendar, Cpu, Layers, User as UserIcon } from 'lucide-react';
import { PredictionResponse } from '../types/api';
import { reportsService } from '../services/reports';
import { formatDate, formatPercent, getSeverityColor, getPredictionStatusBadge } from '../utils/formatters';
import { useAuth } from '../hooks/useAuth';
import { SafetyDisclaimer } from './SafetyDisclaimer';
import { ProbabilityChart } from './ProbabilityChart';
import { GradCAMViewer } from './GradCAMViewer';

interface ReportCardProps {
  data: PredictionResponse;
  originalImageUrl?: string;
  className?: string;
}

export const ReportCard: React.FC<ReportCardProps> = ({ data, originalImageUrl, className = '' }) => {
  const [downloading, setDownloading] = useState(false);
  const [downloadError, setDownloadError] = useState<string | null>(null);
  const { user } = useAuth();

  const userName = data.user_name || (user?.email ? user.email.split('@')[0].replace('.', ' ').replace('_', ' ').toUpperCase() : 'Clinician');
  const userEmail = data.user_email || user?.email || '';

  const handleDownload = async () => {
    if (!data.assessment_id) return;
    setDownloading(true);
    setDownloadError(null);
    try {
      await reportsService.triggerPdfDownload(data.assessment_id);
    } catch {
      setDownloadError('Failed to download PDF report. Ensure backend report engine is available.');
    } finally {
      setDownloading(false);
    }
  };

  const statusBadge = getPredictionStatusBadge(data.prediction_status);
  const severity = getSeverityColor(data.prediction?.class_name);

  return (
    <div className={`rounded-3xl border border-medical-border bg-white p-6 md:p-10 space-y-8 shadow-sm text-left ${className}`}>
      {/* Report Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-medical-border pb-6">
        <div>
          <div className="flex items-center gap-2 text-xs font-mono text-brand-primary uppercase tracking-wider font-bold">
            <Eye className="h-4 w-4" /> EYESCREEN AI Clinical-Grade Report
          </div>
          <h2 className="text-2xl md:text-3xl font-black text-brand-900 mt-1">Screening Summary Report</h2>
          <p className="text-xs text-medical-text-muted mt-1">Generated by deep convolutional neural assessment pipeline.</p>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          <button
            onClick={handleDownload}
            disabled={downloading || !data.assessment_id}
            className="flex items-center gap-2 rounded-xl bg-brand-900 hover:bg-brand-800 px-5 py-2.5 text-sm font-semibold text-white transition shadow-sm disabled:opacity-50"
          >
            <Download className="h-4 w-4" />
            {downloading ? 'Preparing PDF...' : 'Download PDF Report'}
          </button>
        </div>
      </div>

      {downloadError && (
        <div className="rounded-xl border border-medred-primary/30 bg-medred-light p-3 text-xs text-medred-primary font-medium">
          {downloadError}
        </div>
      )}

      {/* Metadata Key-Value Grid */}
      <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
        <div className="rounded-2xl border border-medical-border bg-medical-bg p-3.5">
          <span className="text-[10px] uppercase font-mono text-medical-text-muted block">Assessment ID</span>
          <span className="text-xs font-bold text-brand-900 font-mono mt-1 block break-all">
            {data.assessment_id || 'N/A'}
          </span>
        </div>
        <div className="rounded-2xl border border-medical-border bg-medical-bg p-3.5">
          <span className="text-[10px] uppercase font-mono text-medical-text-muted block">User / Clinician</span>
          <span className="text-xs font-bold text-brand-primary mt-1 block truncate" title={userName}>
            {userName}
          </span>
        </div>
        <div className="rounded-2xl border border-medical-border bg-medical-bg p-3.5">
          <span className="text-[10px] uppercase font-mono text-medical-text-muted block">User Email</span>
          <span className="text-xs font-semibold text-brand-primary mt-1 block truncate" title={userEmail}>
            {userEmail || 'N/A'}
          </span>
        </div>
        <div className="rounded-2xl border border-medical-border bg-medical-bg p-3.5">
          <span className="text-[10px] uppercase font-mono text-medical-text-muted block">Date, Day & Time</span>
          <span className="text-[11px] font-semibold text-medical-text mt-1 block leading-tight">
            {formatDate(data.created_at)}
          </span>
        </div>
        <div className="rounded-2xl border border-medical-border bg-medical-bg p-3.5">
          <span className="text-[10px] uppercase font-mono text-medical-text-muted block">Quality Status</span>
          <span className={`text-xs font-bold mt-1 block ${data.quality?.status === 'GOOD' ? 'text-medgreen-primary' : 'text-medred-primary'}`}>
            {data.quality?.status || 'GOOD'} ({formatPercent(data.quality?.score)})
          </span>
        </div>
      </div>

      {/* Primary Diagnosis / Classification Findings */}
      {(() => {
        const isUncertain = data.prediction_status === 'UNCERTAIN' || data.evaluation?.is_uncertain;
        return (
          <>
            <div className="rounded-2xl border border-medical-border bg-medical-bg p-6 space-y-4">
              <h4 className="text-xs font-semibold uppercase tracking-wider text-medical-text-muted">Diagnostic Classification</h4>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div className="md:col-span-2">
                  <span className="text-xs text-medical-text-muted">Diabetic Retinopathy Category:</span>
                  <div className="flex items-center gap-3 mt-1">
                    <h3 className={`text-2xl md:text-3xl font-black ${isUncertain ? 'text-medorange-dark' : severity.text}`}>
                      {isUncertain
                        ? 'Indeterminate Result — Clinical Review Required'
                        : (data.prediction?.class_name || (data.prediction_status === 'REJECTED' ? 'Quality Rejected (No Prediction)' : 'Inconclusive'))}
                    </h3>
                    {!isUncertain && data.prediction?.class_id !== undefined && (
                      <span className="rounded-lg bg-white border border-medical-border px-2.5 py-1 text-xs font-mono text-brand-900 font-bold shadow-sm">
                        Grade {data.prediction.class_id}
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-medical-text-muted mt-2">
                    {isUncertain
                      ? 'Distribution does not show a clear majority class. Professional evaluation recommended.'
                      : 'Based on standardized clinical grading: 0 (No DR), 1 (Mild DR), 2 (Moderate DR), 3 (Severe DR), 4 (Proliferative DR).'}
                  </p>
                </div>

                <div className="rounded-xl border border-medical-border bg-white p-4 flex flex-col justify-center shadow-sm">
                  <span className="text-xs text-medical-text-muted font-semibold">Model Confidence (Calibrated):</span>
                  <span className="text-2xl font-black text-brand-primary font-mono mt-1">
                    {formatPercent(data.prediction?.confidence)}
                  </span>
                  <span className="text-[10px] text-medical-text-muted mt-1">* Calibrated confidence score — not clinical certainty.</span>
                </div>
              </div>
            </div>

            {/* Class Probabilities Distribution */}
            {data.prediction?.probabilities && (
              <div className="rounded-2xl border border-medical-border bg-medical-bg p-6 space-y-3">
                <h4 className="text-xs font-semibold uppercase tracking-wider text-medical-text-muted">Probability Distribution Across 5 Stages</h4>
                <ProbabilityChart probabilities={data.prediction.probabilities} isUncertain={isUncertain} />
              </div>
            )}
          </>
        );
      })()}

      {/* Grad-CAM Explainability Section */}
      <div className="rounded-2xl border border-medical-border bg-medical-bg p-6 space-y-4">
        <GradCAMViewer
          heatmapUrl={data.explainability?.heatmap_url}
          originalImageUrl={originalImageUrl}
        />
      </div>

      {/* System Technical Metadata */}
      <div className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-medical-border bg-medical-bg px-5 py-3 text-xs text-medical-text-muted">
        <div className="flex items-center gap-2">
          <Cpu className="h-4 w-4 text-brand-primary" />
          <span>Model Architecture: <strong className="text-brand-900">EfficientNet-B0</strong></span>
        </div>
        <div>
          <span>Model Version: <strong className="text-brand-900">v1.0.0-efficientnet</strong></span>
        </div>
        <div>
          <span>Verification: <strong className="text-medgreen-primary font-semibold">Backend Verified</strong></span>
        </div>
      </div>

      {/* Safety Notice */}
      <SafetyDisclaimer />
    </div>
  );
};
